In [67]:
import numpy as np
import pandas as pd

# Load the dataset
X = pd.read_csv('titanic_data.csv')
# Limit to categorical data
X = X.select_dtypes(include=[object])

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [68]:
le = LabelEncoder()
# TODO: For each feature name in X, apply a label encoder using fit_transform
# Reassign this transformed data back into the feature for X!
# for feature in list(X):
# for feature in X.columns.tolist():
for feature in X:
    X[feature] = le.fit_transform(X[feature])

In [51]:
# TODO: create a OneHotEncoder object, and fit it to all of X.
enc = OneHotEncoder()
enc.fit(X)
print "enc.n_values_ is:",enc.n_values_
print "enc.feature_indices_ is:",enc.feature_indices_
#TODO: transform the categorical titanic data, and store the transformed labels in the variable `onehotlabels`
onehotlabels = enc.transform(X).toarray()

enc.n_values_ is: [891   2 681 148   4]
enc.feature_indices_ is: [   0  891  893 1574 1722 1726]

In [24]:
X.columns = list(le.fit_transform(X.columns.tolist()))

In [69]:
X

     Name  Sex  Ticket  Cabin  Embarked
0     108    1     523      0         3
1     190    0     596     82         1
2     353    0     669      0         3
3     272    0      49     56         3
4      15    1     472      0         3
5     554    1     275      0         2
6     515    1      85    130         3
7     624    1     395      0         3
8     412    0     344      0         3
9     576    0     132      0         1
10    727    0     616    146         3
11     95    0      38     50         3
12    729    1     535      0         3
13     28    1     333      0         3
14    840    0     413      0         3
15    359    0     153      0         3
16    682    1     480      0         2
17    867    1     151      0         3
18    839    0     301      0         3
19    512    0     184      0         1
20    273    1     139      0         3
21     80    1     152    112         3
22    523    0     278      0         2
23    765    1      42     14         3
24    626    0     395      0         3
25     44    0     329      0         3
26    240    1     179      0         1
27    260    1      95     64         3
28    605    0     283      0         2
29    813    1     362      0         3
..    ...  ...     ...    ...       ...
861   283    1     221      0         3
862   797    0      88     95         3
863   718    0     568      0         3
864   285    1     120      0         3
865   122    0     126      0         3
866   230    0     632      0         1
867   696    1     590      7         3
868   890    1     309      0         3
869   407    1     344      0         3
870    59    1     387      0         3
871    79    0      54    103         3
872   139    1     502     35         3
873   836    1     303      0         3
874     4    0     575      0         1
875   571    0     195      0         1
876   311    1     504      0         3
877   657    1     358      0         3
878   451    1     363      0         3
879   668    0      59     71         1
880   739    0     115      0         3
881   510    1     394      0         3
882   193    0     508      0         3
883    61    1     565      0         3
884   793    1     650      0         3
885   684    0     480      0         2
886   548    1     101      0         3
887   303    0      14     31         3
888   413    0     675      0         3
889    81    1       8     61         1
890   220    1     466      0         2

[891 rows x 5 columns]